"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { schoolApi } from "@/lib/school-api";

type SchoolClass = { id: string; class_name: string; student_classes: { count: number }[]; teacher_classes: { teacher: { id: string; full_name: string; email: string } | null }[] };
type Teacher = { id: string; full_name: string; email: string; teacher_classes: { class_id: string }[] };
type Student = { student_id: number; class_id: string; student: { id: number; name: string } | null };
type Invite = { id: string; code: string; role: string; expires_at: string; is_active: boolean };

export default function AdminPage() {
  const router = useRouter();
  const [classes, setClasses] = useState<SchoolClass[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]); const [students, setStudents] = useState<Student[]>([]); const [invites, setInvites] = useState<Invite[]>([]);
  const [className, setClassName] = useState(""); const [inviteRole, setInviteRole] = useState("student"); const [expiry, setExpiry] = useState(() => new Date(Date.now() + 7 * 864e5).toISOString().slice(0, 16));
  const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [academicHealth, setAcademicHealth] = useState(0);
  const load = async () => { try { const [classData, assignmentData, inviteData] = await Promise.all([schoolApi<{ classes: SchoolClass[]; academicHealth: number }>("/api/admin/classes"), schoolApi<{ teachers: Teacher[]; students: Student[] }>("/api/admin/assignments"), schoolApi<{ invites: Invite[] }>("/api/admin/invites")]); setClasses(classData.classes); setAcademicHealth(classData.academicHealth); setTeachers(assignmentData.teachers); setStudents(assignmentData.students); setInvites(inviteData.invites); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load school data"); if ((error as Error).message === "Unauthenticated") router.replace("/login"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const averageHealth = useMemo(() => Math.round(academicHealth), [academicHealth]);
  async function createClass(event: FormEvent) { event.preventDefault(); try { await schoolApi("/api/admin/classes", { method: "POST", body: JSON.stringify({ className }) }); setClassName(""); setNotice("Class created."); await load(); } catch (error) { setNotice((error as Error).message); } }
  async function createInvite(event: FormEvent) { event.preventDefault(); try { await schoolApi("/api/admin/invites", { method: "POST", body: JSON.stringify({ role: inviteRole, expiresAt: new Date(expiry).toISOString() }) }); setNotice("Invite code created."); await load(); } catch (error) { setNotice((error as Error).message); } }
  async function assignTeacher(teacherId: string, classId: string) { try { await schoolApi("/api/admin/assignments", { method: "POST", body: JSON.stringify({ teacherId, classId }) }); setNotice("Teacher assigned."); await load(); } catch (error) { setNotice((error as Error).message); } }
  async function reassignStudent(studentId: number, classId: string) { try { await schoolApi("/api/admin/assignments", { method: "PATCH", body: JSON.stringify({ studentId, classId }) }); setNotice("Student class updated."); await load(); } catch (error) { setNotice((error as Error).message); } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-slate-950 text-slate-200">Loading your school…</main>;
  return <main className="min-h-screen bg-slate-950 px-4 py-8 text-slate-100 sm:px-8"><div className="mx-auto max-w-7xl space-y-8"><header className="rounded-3xl border border-white/10 bg-gradient-to-br from-indigo-600 via-violet-600 to-slate-900 p-8 shadow-2xl"><p className="text-sm font-medium uppercase tracking-[0.2em] text-indigo-200">VidyaLens school OS</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Administration</h1><p className="mt-2 max-w-xl text-indigo-100">Manage people, classes, and secure school access from one calm workspace.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Students", students.length, "Enrolled learners"], ["Teachers", teachers.length, "Teaching team"], ["Classes", classes.length, "Active classrooms"], ["Academic health", `${averageHealth}%`, "Based on subject scores"]].map(([label, value, hint]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></div>)}</section>
    {notice && <p className="rounded-xl border border-indigo-400/30 bg-indigo-400/10 px-4 py-3 text-sm text-indigo-100">{notice}</p>}
    <section className="grid gap-6 lg:grid-cols-2"><form onSubmit={createClass} className="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 className="text-lg font-semibold">Create class</h2><p className="mt-1 text-sm text-slate-400">Classes keep staff and learner access scoped correctly.</p><div className="mt-5 flex gap-3"><input required value={className} onChange={(e) => setClassName(e.target.value)} placeholder="e.g. Grade 10 A" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5 outline-none focus:border-indigo-400"/><button className="rounded-xl bg-indigo-500 px-4 py-2.5 font-medium hover:bg-indigo-400">Add</button></div></form>
      <form onSubmit={createInvite} className="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 className="text-lg font-semibold">Create invite code</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><select value={inviteRole} onChange={(e) => setInviteRole(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5"><option value="student">Student</option><option value="teacher">Teacher</option><option value="admin">Admin</option></select><input required type="datetime-local" value={expiry} onChange={(e) => setExpiry(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5"/></div><button className="mt-3 rounded-xl bg-indigo-500 px-4 py-2.5 font-medium hover:bg-indigo-400">Generate code</button></form></section>
    <section className="overflow-hidden rounded-2xl border border-white/10 bg-slate-900"><div className="border-b border-white/10 p-6"><h2 className="text-lg font-semibold">Classes</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-800/70 text-slate-400"><tr><th className="px-6 py-3">Class</th><th className="px-6 py-3">Students</th><th className="px-6 py-3">Teachers</th><th className="px-6 py-3">Assign teacher</th></tr></thead><tbody>{classes.map((item) => <tr key={item.id} className="border-t border-white/5"><td className="px-6 py-4 font-medium">{item.class_name}</td><td className="px-6 py-4">{item.student_classes?.[0]?.count ?? 0}</td><td className="px-6 py-4 text-slate-400">{item.teacher_classes.map((x) => x.teacher?.full_name).filter(Boolean).join(", ") || "—"}</td><td className="px-6 py-4"><select defaultValue="" onChange={(e) => e.target.value && void assignTeacher(e.target.value, item.id)} className="rounded-lg border border-slate-700 bg-slate-800 px-2 py-1.5"><option value="" disabled>Choose teacher</option>{teachers.map((teacher) => <option value={teacher.id} key={teacher.id}>{teacher.full_name}</option>)}</select></td></tr>)}{classes.length === 0 && <tr><td colSpan={4} className="px-6 py-8 text-slate-400">Create your first class to get started.</td></tr>}</tbody></table></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 className="font-semibold">Students by class</h2><div className="mt-4 space-y-3">{students.map(({ student_id, student, class_id }) => <div key={student_id} className="flex items-center justify-between gap-4 rounded-xl bg-slate-800/70 p-3"><span>{student?.name || "Student"}</span><select value={class_id} onChange={(e) => void reassignStudent(student_id, e.target.value)} className="rounded-lg border border-slate-700 bg-slate-900 px-2 py-1.5">{classes.map((item) => <option value={item.id} key={item.id}>{item.class_name}</option>)}</select></div>)}{students.length === 0 && <p className="text-sm text-slate-400">No students have joined yet.</p>}</div></div><div className="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 className="font-semibold">Active invite codes</h2><div className="mt-4 space-y-3">{invites.slice(0, 6).map((invite) => <div key={invite.id} className="flex items-center justify-between rounded-xl bg-slate-800/70 p-3"><div><code className="font-semibold tracking-widest text-indigo-200">{invite.code}</code><p className="mt-1 text-xs capitalize text-slate-400">{invite.role} · expires {new Date(invite.expires_at).toLocaleDateString()}</p></div><span className={invite.is_active ? "text-xs text-emerald-400" : "text-xs text-slate-500"}>{invite.is_active ? "Active" : "Inactive"}</span></div>)}{invites.length === 0 && <p className="text-sm text-slate-400">No invite codes yet.</p>}</div></div></section>
  </div></main>;
}
