"use client";

import { FormEvent, useState } from "react";
import { supabase } from "@/lib/supabase";
import { schoolApi } from "@/lib/school-api";

type InviteClass = { school_name: string; role: "admin" | "teacher" | "student"; class_id: string | null; class_name: string | null };

export default function JoinPage() {
  const [code, setCode] = useState(""); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [classId, setClassId] = useState(""); const [invite, setInvite] = useState<InviteClass[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const role = invite[0]?.role; const classes = invite.filter((row) => row.class_id);
  async function verifyCode() { setBusy(true); setMessage(""); const { data, error } = await supabase.rpc("invite_classes", { p_code: code.trim().toUpperCase() }); if (error || !data?.length) { setInvite([]); setMessage(error?.message || "That invite code is invalid, inactive, or expired."); } else { setInvite(data as InviteClass[]); setMessage(`Joining ${data[0].school_name} as ${data[0].role}.`); } setBusy(false); }
  async function join(event: FormEvent) { event.preventDefault(); if (!role) return setMessage("Verify your invite code first."); if (role === "student" && !classId) return setMessage("Choose your class."); setBusy(true); try { const { data, error } = await supabase.auth.signUp({ email, password }); if (error) throw error; if (!data.session) { setMessage("Check your email to confirm your account, then sign in and open this join link again to finish joining."); return; } await schoolApi("/api/onboarding/redeem", { method: "POST", body: JSON.stringify({ code, fullName, classId }) }); window.location.href = role === "student" ? "/" : `/${role}`; } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create account"); } finally { setBusy(false); } }
  return <main className="grid min-h-screen place-items-center bg-slate-950 p-4 text-slate-100"><form onSubmit={join} className="w-full max-w-lg rounded-3xl border border-white/10 bg-slate-900 p-7 shadow-2xl"><p className="text-sm font-medium uppercase tracking-[.2em] text-indigo-300">VidyaLens</p><h1 className="mt-2 text-3xl font-bold">Join your school</h1><p className="mt-2 text-sm text-slate-400">Your school administrator will give you a unique invite code.</p><div className="mt-6 flex gap-2"><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="ABC12345" maxLength={8} className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5 font-mono tracking-widest outline-none focus:border-indigo-400"/><button type="button" disabled={busy || code.length !== 8} onClick={() => void verifyCode()} className="rounded-xl bg-slate-700 px-4 font-medium hover:bg-slate-600 disabled:opacity-50">Verify</button></div>{role && <><div className="mt-5 grid gap-3"><input required value={fullName} onChange={(e) => setFullName(e.target.value)} placeholder="Full name" className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5"/><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email address" className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5"/><input required type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Create a password" className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5"/>{role === "student" && <select required value={classId} onChange={(e) => setClassId(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5"><option value="" disabled>Select your class</option>{classes.map((item) => <option key={item.class_id} value={item.class_id!}>{item.class_name}</option>)}</select>}</div><button disabled={busy} className="mt-5 w-full rounded-xl bg-indigo-500 px-4 py-3 font-semibold hover:bg-indigo-400 disabled:opacity-50">{busy ? "Working…" : `Join as ${role}`}</button></>}{message && <p className="mt-4 rounded-xl bg-slate-800 px-3 py-2.5 text-sm text-slate-300">{message}</p>}</form></main>;
}
