import Link from "next/link";

const features = [
  ["AI study planning", "Turn subjects, exams, and real availability into a focused daily plan."],
  ["Academic Health Score", "See a clear signal of progress and the next subject that needs attention."],
  ["Connected classrooms", "Give teachers visibility into classes, marks, schedules, and study completion."],
];

export default function LandingPage() {
  return <main className="min-h-screen overflow-x-hidden bg-slate-950 text-slate-100">
    <div className="absolute inset-x-0 top-0 -z-0 h-[38rem] bg-[radial-gradient(circle_at_25%_10%,rgba(99,102,241,.26),transparent_32%),radial-gradient(circle_at_75%_20%,rgba(14,165,233,.16),transparent_28%)]" />
    <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="text-xl font-bold tracking-tight">Vidya<span className="text-indigo-300">Lens</span></Link><nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><Link href="#features" className="hover:text-white">Features</Link><Link href="#how-it-works" className="hover:text-white">How It Works</Link></nav><div className="flex items-center gap-3 text-sm"><Link href="/login" className="rounded-lg px-3 py-2 font-medium text-slate-200 hover:bg-white/10">Login</Link><Link href="/register-school" className="rounded-lg bg-indigo-500 px-4 py-2 font-semibold text-white shadow-lg shadow-indigo-500/25 hover:bg-indigo-400">Register School</Link></div></header>
    <section className="relative z-10 mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pb-32 lg:pt-24"><div><p className="mb-5 inline-flex rounded-full border border-indigo-300/20 bg-indigo-400/10 px-3 py-1 text-sm font-medium text-indigo-200">A clearer path to academic growth</p><h1 className="max-w-3xl text-5xl font-bold leading-[1.04] tracking-tight sm:text-6xl">Every learner deserves a plan that <span className="text-indigo-300">adapts.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">VidyaLens brings students, teachers, and school leaders into one intelligent learning workspace—built around what each learner needs next.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/register-school" className="rounded-xl bg-indigo-500 px-5 py-3 font-semibold shadow-xl shadow-indigo-500/25 hover:bg-indigo-400">Register your school</Link><Link href="#features" className="rounded-xl border border-white/15 px-5 py-3 font-semibold hover:bg-white/10">Explore the platform</Link></div><p className="mt-5 text-sm text-slate-400">Already invited? <Link href="/join" className="text-indigo-300 hover:text-indigo-200">Join with an invite code</Link>.</p></div><div className="rounded-3xl border border-white/10 bg-slate-900/75 p-5 shadow-2xl shadow-indigo-950/50 backdrop-blur"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-sm text-slate-400">Academic Health</p><p className="text-3xl font-bold">82 <span className="text-base font-medium text-emerald-300">+8 this week</span></p></div><div className="rounded-xl bg-emerald-400/10 px-3 py-2 text-sm font-semibold text-emerald-300">On track</div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/5 p-4"><p className="text-sm text-slate-400">Current streak</p><p className="mt-2 text-2xl font-bold">🔥 12 days</p></div><div className="rounded-2xl bg-white/5 p-4"><p className="text-sm text-slate-400">Weekly consistency</p><p className="mt-2 text-2xl font-bold">86%</p></div></div><div className="mt-4 rounded-2xl border border-indigo-400/20 bg-indigo-400/10 p-4"><p className="font-semibold">Today’s intelligent focus</p><p className="mt-1 text-sm text-slate-300">Review Physics concepts before your next exam, then complete a focused Maths session.</p></div></div></section>
    <section id="features" className="border-y border-white/10 bg-slate-900/50 py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-indigo-300">One platform, shared clarity</p><h2 className="mt-3 max-w-2xl text-3xl font-bold sm:text-4xl">Everything that makes progress visible.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(([title, description]) => <article key={title} className="rounded-2xl border border-white/10 bg-slate-950/60 p-6"><div className="mb-5 h-10 w-10 rounded-xl bg-indigo-500/20" /><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 leading-7 text-slate-400">{description}</p></article>)}</div></div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-indigo-300">How VidyaLens works</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">From school setup to stronger outcomes.</h2></div><ol className="grid gap-4 sm:grid-cols-3">{[["01","Set up your school","Create your workspace and invite your teaching team."],["02","Connect the classroom","Teachers manage classes, marks, exam dates, and student support."],["03","Guide every learner","Students receive AI planning and clear progress signals."]].map(([number, title, description]) => <li key={number} className="rounded-2xl border border-white/10 p-5"><p className="font-mono text-sm text-indigo-300">{number}</p><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p></li>)}</ol></div></section>
    <section className="bg-indigo-500 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-3"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-indigo-100">Built for the real school day</p><h2 className="mt-3 text-3xl font-bold">Intelligence that supports every role.</h2></div><div><h3 className="text-xl font-semibold">AI-powered study planning</h3><p className="mt-3 leading-7 text-indigo-100">Plans respond to subjects, exams, availability, completed sessions, and confidence—not generic schedules.</p></div><div><h3 className="text-xl font-semibold">Teacher analytics & health scores</h3><p className="mt-3 leading-7 text-indigo-100">Teachers see the signals behind student progress while leaders get a school-wide view of academic health.</p></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-slate-900 p-8"><p className="text-indigo-300">Academic Health Score</p><h2 className="mt-3 text-3xl font-bold">Make support proactive.</h2><p className="mt-4 max-w-xl leading-7 text-slate-400">VidyaLens turns subject performance and learning activity into an understandable signal, so students and teachers can act before a setback becomes a pattern.</p></article><article className="rounded-3xl border border-white/10 bg-slate-900 p-8"><p className="text-indigo-300">What schools will say</p><blockquote className="mt-5 text-xl leading-8 text-slate-200">“VidyaLens made it easier to turn performance data into a supportive conversation with every learner.”</blockquote><p className="mt-5 text-sm text-slate-400">— Educator testimonial placeholder</p></article></div></section>
    <section id="contact" className="border-t border-white/10 bg-slate-900/50"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-16 sm:px-8 md:flex-row md:items-center md:justify-between"><div><h2 className="text-3xl font-bold">Ready to bring learning into focus?</h2><p className="mt-2 text-slate-400">Start your school workspace and invite your team when you are ready.</p></div><Link href="/register-school" className="w-fit rounded-xl bg-indigo-500 px-5 py-3 font-semibold hover:bg-indigo-400">Register School</Link></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><p>© {new Date().getFullYear()} VidyaLens. Learning, made visible.</p><div className="flex gap-5"><Link href="/login" className="hover:text-slate-300">Login</Link><Link href="/join" className="hover:text-slate-300">Join a school</Link><Link href="#contact" className="hover:text-slate-300">Contact</Link></div></footer>
  </main>;
}
