-- VidyaLens School Administration
-- Additive migration for an existing database where public.schools.id and
-- public.students.id are bigint. It deliberately does not create or alter
-- schools, students, profiles, subjects, or timetable_entries.

do $$
begin
  if to_regclass('public.schools') is null then
    raise exception 'Expected existing table public.schools was not found';
  end if;
  if to_regclass('public.students') is null then
    raise exception 'Expected existing table public.students was not found';
  end if;
  if (select data_type from information_schema.columns where table_schema = 'public' and table_name = 'schools' and column_name = 'id') <> 'bigint' then
    raise exception 'public.schools.id must be bigint for this migration';
  end if;
  if (select data_type from information_schema.columns where table_schema = 'public' and table_name = 'students' and column_name = 'id') <> 'bigint' then
    raise exception 'public.students.id must be bigint for this migration';
  end if;
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'students' and column_name = 'user_id')
     or not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'students' and column_name = 'name')
     or not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'students' and column_name = 'school_id') then
    raise exception 'Expected students.user_id, students.name, and students.school_id columns were not found';
  end if;
end $$;

-- profiles is intentionally not referenced. Its shape varies between VidyaLens
-- installations, and membership is now represented by the role tables below.
create table if not exists public.school_admins (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (school_id, user_id),
  unique (user_id)
);

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) > 0),
  email text not null,
  created_at timestamptz not null default now(),
  unique (user_id),
  unique (school_id, email)
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  class_name text not null check (char_length(trim(class_name)) > 0),
  created_at timestamptz not null default now(),
  unique (school_id, class_name)
);

create table if not exists public.teacher_classes (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (teacher_id, class_id)
);

create table if not exists public.student_classes (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (student_id)
);

create table if not exists public.invite_codes (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  code text not null unique check (code = upper(code) and code ~ '^[A-Z0-9]{8}$'),
  role text not null check (role in ('admin', 'teacher', 'student')),
  expires_at timestamptz not null,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.marks (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  teacher_id bigint not null references public.teachers(id) on delete restrict,
  subject_id bigint references public.subjects(id) on delete set null,
  assessment_name text not null,
  score numeric(6,2) not null check (score >= 0),
  max_score numeric(6,2) not null check (max_score > 0 and score <= max_score),
  assessed_at date not null default current_date,
  created_at timestamptz not null default now()
);

-- Add this table even if legacy completion tracking exists: it avoids making
-- assumptions about legacy columns while providing a stable staff reporting API.
create table if not exists public.study_session_completions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  timetable_entry_id bigint references public.timetable_entries(id) on delete set null,
  completed boolean not null default true,
  completed_at timestamptz not null default now(),
  unique (student_id, timetable_entry_id)
);

create index if not exists school_admins_school_id_idx on public.school_admins(school_id);
create index if not exists teachers_school_id_idx on public.teachers(school_id);
create index if not exists classes_school_id_idx on public.classes(school_id);
create index if not exists teacher_classes_class_id_idx on public.teacher_classes(class_id);
create index if not exists student_classes_class_id_idx on public.student_classes(class_id);
create index if not exists invite_codes_school_active_idx on public.invite_codes(school_id, is_active, expires_at);
create index if not exists marks_student_id_idx on public.marks(student_id);
create index if not exists study_session_completions_student_id_idx on public.study_session_completions(student_id);

create or replace function public.is_school_admin(p_school_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from school_admins where school_id = p_school_id and user_id = auth.uid());
$$;

create or replace function public.is_assigned_teacher(p_class_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from teachers t join teacher_classes tc on tc.teacher_id = t.id where t.user_id = auth.uid() and tc.class_id = p_class_id);
$$;

create or replace function public.redeem_invite_code(p_code text, p_full_name text, p_class_id bigint default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_invite public.invite_codes%rowtype;
  v_user_id uuid := auth.uid();
  v_email text;
  v_student_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication is required'; end if;
  select * into v_invite from public.invite_codes where code = upper(trim(p_code)) and is_active and expires_at > now() for update;
  if not found then raise exception 'This invite code is invalid, inactive, or expired'; end if;
  if v_invite.role = 'student' and p_class_id is null then raise exception 'A class is required for students'; end if;
  if p_class_id is not null and not exists (select 1 from public.classes where id = p_class_id and school_id = v_invite.school_id) then raise exception 'The selected class does not belong to this school'; end if;
  if v_invite.role = 'admin' then
    insert into public.school_admins (school_id, user_id) values (v_invite.school_id, v_user_id) on conflict do nothing;
  elsif v_invite.role = 'teacher' then
    select email into v_email from auth.users where id = v_user_id;
    insert into public.teachers (school_id, user_id, full_name, email) values (v_invite.school_id, v_user_id, trim(p_full_name), v_email)
    on conflict (user_id) do update set school_id = excluded.school_id, full_name = excluded.full_name, email = excluded.email;
  else
    insert into public.students (user_id, name, school_id) values (v_user_id, trim(p_full_name), v_invite.school_id)
    on conflict (user_id) do update set name = excluded.name, school_id = excluded.school_id returning id into v_student_id;
    if v_student_id is null then select id into v_student_id from public.students where user_id = v_user_id; end if;
    insert into public.student_classes (student_id, class_id) values (v_student_id, p_class_id)
    on conflict (student_id) do update set class_id = excluded.class_id;
  end if;
  return jsonb_build_object('school_id', v_invite.school_id, 'role', v_invite.role);
end;
$$;

create or replace function public.invite_classes(p_code text)
returns table (school_name text, role text, class_id bigint, class_name text)
language sql stable security definer set search_path = public as $$
  select s.name, i.role, c.id, c.class_name from public.invite_codes i join public.schools s on s.id = i.school_id left join public.classes c on c.school_id = i.school_id
  where i.code = upper(trim(p_code)) and i.is_active and i.expires_at > now() order by c.class_name;
$$;

create or replace function public.school_academic_health(p_school_id bigint)
returns numeric language sql stable security definer set search_path = public as $$
  select coalesce(round(avg(su.score)::numeric, 1), 0) from public.students st join public.subjects su on su.student_id = st.id
  where st.school_id = p_school_id and (public.is_school_admin(p_school_id) or exists (select 1 from public.teachers t where t.school_id = p_school_id and t.user_id = auth.uid()));
$$;

grant execute on function public.redeem_invite_code(text, text, bigint) to authenticated;
grant execute on function public.invite_classes(text) to anon, authenticated;
grant execute on function public.school_academic_health(bigint) to authenticated;

alter table public.school_admins enable row level security;
alter table public.teachers enable row level security;
alter table public.classes enable row level security;
alter table public.teacher_classes enable row level security;
alter table public.student_classes enable row level security;
alter table public.invite_codes enable row level security;
alter table public.marks enable row level security;
alter table public.study_session_completions enable row level security;

create policy "admins view school admins" on public.school_admins for select using (user_id = auth.uid() or public.is_school_admin(school_id));
create policy "admins view teachers" on public.teachers for select using (user_id = auth.uid() or public.is_school_admin(school_id));
create policy "admins manage teachers" on public.teachers for all using (public.is_school_admin(school_id)) with check (public.is_school_admin(school_id));
create policy "school members view classes" on public.classes for select using (public.is_school_admin(school_id) or exists (select 1 from public.teachers where user_id = auth.uid() and school_id = classes.school_id) or exists (select 1 from public.students where user_id = auth.uid() and school_id = classes.school_id));
create policy "admins manage classes" on public.classes for all using (public.is_school_admin(school_id)) with check (public.is_school_admin(school_id));
create policy "staff view teacher classes" on public.teacher_classes for select using (public.is_assigned_teacher(class_id) or exists (select 1 from public.classes where id = class_id and public.is_school_admin(school_id)));
create policy "admins manage teacher classes" on public.teacher_classes for all using (exists (select 1 from public.classes where id = class_id and public.is_school_admin(school_id))) with check (exists (select 1 from public.classes where id = teacher_classes.class_id and public.is_school_admin(school_id)));
create policy "members view student classes" on public.student_classes for select using (exists (select 1 from public.students where id = student_id and user_id = auth.uid()) or public.is_assigned_teacher(class_id) or exists (select 1 from public.classes where id = class_id and public.is_school_admin(school_id)));
create policy "admins manage student classes" on public.student_classes for all using (exists (select 1 from public.classes where id = class_id and public.is_school_admin(school_id))) with check (exists (select 1 from public.classes where id = student_classes.class_id and public.is_school_admin(school_id)));
create policy "admins manage invites" on public.invite_codes for all using (public.is_school_admin(school_id)) with check (public.is_school_admin(school_id));
create policy "staff view marks" on public.marks for select using (exists (select 1 from public.student_classes sc where sc.student_id = marks.student_id and (public.is_assigned_teacher(sc.class_id) or exists (select 1 from public.classes c where c.id = sc.class_id and public.is_school_admin(c.school_id)))));
create policy "teachers create marks" on public.marks for insert with check (teacher_id in (select id from public.teachers where user_id = auth.uid()) and exists (select 1 from public.student_classes sc where sc.student_id = marks.student_id and public.is_assigned_teacher(sc.class_id)));
create policy "students manage own completions" on public.study_session_completions for all using (exists (select 1 from public.students where id = student_id and user_id = auth.uid())) with check (exists (select 1 from public.students where id = study_session_completions.student_id and user_id = auth.uid()));
create policy "staff view completions" on public.study_session_completions for select using (exists (select 1 from public.student_classes sc where sc.student_id = study_session_completions.student_id and public.is_assigned_teacher(sc.class_id)) or exists (select 1 from public.students s where s.id = study_session_completions.student_id and public.is_school_admin(s.school_id)));
